### ISSUE TITLE
Issue with the CSSLoader backend

### ISSUE THREAD

**Issue by CruxisMithos** [beebls/CSSLoader-Desktop#16]
My CSSLoader on Windows will not start now. There was an open to update the backend, and I did so but now CSSLoader appears to be stuck. I noticed a trojan warning popped up initially when the backend was installing. Now it is stuck on the "Welcome to CSSLoader" screen.

**Comment by CruxisMithos** [comment]
Trojan:Script/Wacatac.H!ml is the trojan popup that I see select install backend.

**Comment by suchmememanyskill** [comment]
Please update your microsoft defender antivirus definitions. Intelligence version 1.393.1183.0 (23/07/2023) does not trigger an AV warning for me.

**Comment by CruxisMithos** [comment]
Thanks, this has been resolved. I also dropped a chat on discord.
