### ISSUE TITLE
Feature Request: CSS Load Order

### ISSUE THREAD

**Issue by Skyyblaze** [beebls/CSSLoader-Desktop#17]
Hi, I absolutely love CSSLoader so that I can finally theme the new Steam UI. The only issue I have with it, I wish the application had a load-order.

I'm using a theme called "Main Window Image" to add a background-image to my Steam Desktop UI but unfortunately this makes some text very hard to read due to the Text Colors. So I'm loading another theme called "Color Master" which allows me to adjust each and every color. Unfortunately though Color Master also sets the background of Steam to an opaque color so I can't see my background-image anymore.

If I disable and re-enable "Main Window Image" while "Color Master" is already active they play well together but unfortunately this doesn't persist through restarts. Hence I would love if CSSLoader had a load-order for themes so I can tell it to load "Main Window Image" last.

**Comment by suchmememanyskill** [comment]
We already have such a feature implemented, although it isn't accessible in the UI. You can create a file called `PRIORITY` in a theme's folder and writing a number inside it (like `999`) to manually set the load order; the higher the number, the more priority the css has. Don't forget to reload the themes after creating such a file

Source here: https://github.com/suchmememanyskill/SDH-CssLoader/blob/main/css_theme.py#L28

**Comment by Skyyblaze** [comment]
Oh I see, that worked like a charm, thanks! :)

**Comment by beebls** [comment]
Marking closed as it seems suchmeme has helped you out.
