### ISSUE TITLE
trojan computer virus detected : Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Simon423** [beebls/CSSLoader-Desktop#22]
It is flagged by windows secruity and I don't feel comfortable installing it
Trojan:Script/Wacatac.B!ml

**Comment by suchmememanyskill** [comment]
This is likely from the backend, i assume? (executable name is something like cssloader-standalone-headless.exe). If so, pyinstaller, the packager we use, unfortunately also is used commonly in malware, which leads to pyinstaller itself being treated as malware.

https://github.com/suchmememanyskill/SDH-CssLoader feel free to read through the source code and compile it yourself
