### ISSUE TITLE
Feature Request: Theme Priority GUI 

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [beebls/CSSLoader-Desktop#24]
While looking for theme load order options I found #17, which mentions that this feature exists but isn't available in the UI.
I would love to see that value (if present for a theme) to be displayed in the Theme Management GUI or even better have the setting exposed in the theme settings screen. 

Also thanks to everyone involved with this project.

**Comment by suchmememanyskill** [comment]
I don't know if this is a good idea to implement. Very rarely would this benefit the user, and i think users will mistake the load order to be more powerful than it actually is. I think users will mistake that they can solve any visual conflicts between themes with this rather than the (rare) css rule order of themes that happen to have the same rules. Meaning we get issue reports for issues that are not our fault.

**Comment by EMERALD0874** [comment]
I agree with @suchmememanyskill, I think it's a good idea to keep a prioritization feature accessible only to theme developers who know what they're doing is very specific. For example, it makes sense for something specific like Clean Gameview to override something like Obsidian.

We don't want people reporting theme incompatibility or CSS Loader issues because they didn't prioritize their themes right. Theme developers who work on large themes (ex. Obsidian) already get reports from time to time that aren't their fault or should be fixed by the more specific theme dev.

**Comment by EMERALD0874** [comment]
If you'd like us to consider this feature, please provide some examples for discussion. Otherwise, we consider this a feature that should be restricted to developers who know what they're doing. We could look into some "advanced user" mode where this is accessible, but I don't think anything like that is in our planning.

**Comment by suchmememanyskill** [comment]
> Well it would have helped with making me aware of the system and it would have saved me a few hours trying to figure out a way to fix my issues. Because 95% of my compatibility issues I faced were fixed by using that functionality. And for the others I had to tweak the theme itself to let the lower priority theme keep its styling.
> It feels weird and also kinda annoying that an essential feature was at least for my experience hidden away in a closed issue (that I only found per chance because I wanted to make sure that I am not making a duplicate issue).

Such incompatibilities are better fixed at a theme level than the load order level. Which themes are conflicting?

**Comment by EzioTheDeadPoet** [comment]
- [Metro by Rose](https://share.deckthemes.com/2b449cfc-ba7d-45bf-a540-a049909748eb)
- [Color Master](https://share.deckthemes.com/0f650275-3e2f-47f2-bf3c-8ecae2324a91)
  - [Desktop Colored Toggles](https://share.deckthemes.com/651f2f21-d72a-47e9-81e3-e356c311414a)

The fixes I needed to make them work together were to load "Color Master" and "Desktop Colored Toggles" after "Metro by Rose" and to comment out the account and notification color changes for the top navigation bar made by "Color Master" (Doing it only for notifications fixes the main issue where the notification icon feels like it is one pixel down in it's display, but to use Color Master as a tool to recolor the Metro Theme as it was originally I also had to disable the color changes for the account button).

The game hover info popup is still not looking nice in that combination but the Metro theme has a toggle to disable that preview which is enough of a fix for me.

**Comment by PartyWumpus** [comment]
You could mention it on the wiki somewhere, instead of keeping it hidden in a closed github issue. (not sure how many people actually read documentation though...)

**Comment by EzioTheDeadPoet** [comment]
There will also likely be issues with [Main Window Image](https://deckthemes.com/themes/view?themeId=3b242a59-0911-4551-a4b0-6117e51fc6d6) since the metro theme also has changes to the background. 
Tho I am not using this theme.

Also I am not sure but does the priority file allow for `-1` as well ? Cause compared with most themes you would want to load Metro 1st and then tweak it further with other themes.

**Comment by suchmememanyskill** [comment]
> * [Metro by Rose](https://share.deckthemes.com/2b449cfc-ba7d-45bf-a540-a049909748eb)
> 
>     * [Color Master](https://share.deckthemes.com/0f650275-3e2f-47f2-bf3c-8ecae2324a91)
>       
>       * [Desktop Colored Toggles](https://share.deckthemes.com/651f2f21-d72a-47e9-81e3-e356c311414a)
> 
> 
> The fixes I needed to make them work together were to load "Color Master" and "Desktop Colored Toggles" after "Metro by Rose" and to comment out the account and notification color changes for the top navigation bar made by "Color Master" (Doing it only for notifications fixes the main issue where the notification icon feels like it is one pixel down in it's display, but to use Color Master as a tool to recolor the Metro Theme as it was originally I also had to disable the color changes for the account button).
> 
> The game hover info popup is still not looking nice in that combination but the Metro theme has a toggle to disable that preview which is enough of a fix for me.

Stacking multiple full reskins of steam on top of eachother yields weird results. I'm not too suprised about that one. I think there's limits to what we can do on our end. If you want more customalisation, learn css.

> You could mention it on the wiki somewhere, instead of keeping it hidden in a closed github issue. (not sure how many people actually read documentation though...)

Good point. I can probably note it down somewhere

**Comment by EzioTheDeadPoet** [comment]
> You could mention it on the wiki somewhere, instead of keeping it hidden in a closed github issue. (not sure how many people actually read documentation though...)

As someone who knows how much it "hurts" when people don't read the documentation you spent a long time writing, try to read all the documentation that I can find that applies to my use of the software. 
So in this case I was reading what is expected of a theme user to read not a theme creator.
So I agree having advanced user features addressed somewhere in a "This you can try to make your themes work better together" documentation somewhere would also have helped me.

**Comment by suchmememanyskill** [comment]
![image](https://github.com/beebls/CSSLoader-Desktop/assets/38142618/5c664803-8931-4487-8d0b-4a77bd09ee43)
https://docs.deckthemes.com/CSSLoader/Features/#load-order

Added
