### ISSUE TITLE
The Backend does not download.

### ISSUE THREAD

**Issue by MagmaBro123** [beebls/CSSLoader-Desktop#25]
Title.

![image](https://github.com/beebls/CSSLoader-Desktop/assets/51277766/7380ec50-eb95-4870-8d30-9779bec10300)

Windows 10, CSS Loader 1.1.0.

**Comment by suchmememanyskill** [comment]
Is defender blocking the download?

**Comment by MagmaBro123** [comment]
No. Don't know why, but it took 3 hours for it to snap out of whatever was going on.

**Comment by beebls** [comment]
Closing as this thread has gone stale
