### ISSUE TITLE
Custom colors doesn't work with the Steam Families Beta

### ISSUE THREAD

**Issue by 0JXI0** [beebls/CSSLoader-Desktop#40]
https://github.com/user-attachments/assets/05f57fb4-3612-477f-aefb-daa3f64e33a0

**Comment by suchmememanyskill** [comment]
This is not an issue with the loader, this is an issue with the specific theme. This is not the place to make bug reports for themes

**Comment by 0JXI0** [comment]
I feel dumber than dumb right now, I had tried it with only two themes and thought it was persisting across themes. Thanks for the info

**Comment by suchmememanyskill** [comment]
I just submitted an update for main window gradient, just need to wait for approval
